---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-app-hub
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-app-hub
  template:
    metadata:
      labels:
        app: wil-app-hub
    spec:
      containers:
        - name: app
          image: "wil42/playground:v1"
          ports:
            - containerPort: 8888
---

apiVersion: v1
kind: Service
metadata:
  name: wil-app-hub-service
  namespace: dev
spec:
  selector:
    app: wil-app-hub
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
