apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-iot-p3
  namespace: dev
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: iot-argo-service 
                port:
                  number: 8888
